### ISSUE TITLE
Be mindful of provenance in `LCellOwner::rw2`

### ISSUE THREAD

**Issue by Karrq** [CeleritasCelery/rune#12]
(First, very cool project, I hope I'll be able to contribute in the future!)

Hi, I was looking at `LCellOwner` after your recent blog post and noticed [the comparison on the `LCell`'s pointers in `rw2`](https://github.com/CeleritasCelery/rune/blob/master/src/arena/cell.rs#L33) to avoid aliasing mutable borrows, and I was wondering if you had taken into consideration pointer provenance?

I wouldn't do a good job at explaining the concept so I'll refer you to some articles (series, really) from very smart people and the nightly docs:
* https://www.ralfj.de/blog/2018/07/24/pointers-and-bytes.html
* https://gankra.github.io/blah/fix-rust-pointers/#distinguish-pointers-and-addresses
* https://github.com/rust-lang/rust/issues/95228
* https://doc.rust-lang.org/nightly/std/ptr/index.html#strict-provenance

But in short pointers shouldn't be casted to integers directly and [.addr](https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.addr) should be used instead (or the [stable polyfill's](https://docs.rs/sptr/0.3.1/sptr/trait.Strict.html#tymethod.addr))

**Comment by CeleritasCelery** [comment]
Thanks for the issue! I am glad you find it interesting. I hope you can [contribute](https://github.com/CeleritasCelery/rune#contributing) in the future as well!

As far as the issue with strict provenance, it is worse then you realize 😱. Currently all of our tagged objects are using ptr->int->ptr conversions.

https://github.com/CeleritasCelery/rune/blob/d8698256ef61dc3340d3e5b68d605f90a5bd0336/src/object/data.rs#L36-L54

This is due to how I defined them as 7-byte arrays. That will all need to change in order to comply with strict provenance (which I want to do). As you pointed out there are other places in the code that need to be fixed as well. You are welcome to create PR for `LCellOwner` if you want (and add the `sptr` crate).
