### ISSUE TITLE
defvar! not working inside a function body

### ISSUE THREAD

**Issue by declantsien** [CeleritasCelery/rune#30]
- This works

```
fn main() {
    defvar!(SCRIPT_REPRESENTATIVE_CHARS);
...
```

- This does not work

```
defvar!(SCRIPT_REPRESENTATIVE_CHARS);
fn main() {

...
```

**Comment by declantsien** [comment]
By 'not working', I mean there is no `crate::core::env::sym::SOME_SYMBOL_NAME`.
And `(message some-symbole-name)` in the repl prints `Error: Void variable`

**Comment by CeleritasCelery** [comment]
This is sort of intentional. variables declared with `defvar` cannot be scoped to a function so we expect them to get declared with "module level" scope. I feel like putting them inside a function might be confusing, because you might expect that these behave like normal rust variables. Instead they handled completely by `build.rs`:

https://github.com/CeleritasCelery/rune/blob/f487145a50c9bfbb0d8cfe477effa4bf1e87c87b/build.rs#L94-L102

We just search any line that starts with `defvar`.

**Comment by declantsien** [comment]
I see. Closing.
